### IMPORTING LIBARIES

In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### READING DATA

In [44]:
df=pd.read_csv('fake.csv')
df

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016"
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016"

In [45]:
df.sample(10)

,title,text,subject,date
16747,DISNEY WORKER To Testify About Having To Train...,FINALLY! The H-1b Visa program has been so abu...,Government News,"Feb 25, 2016"
16954,ISIS Releases New Video Making Clear Their Mis...,"ISIS released a new video yesterday, where the...",Government News,"Nov 26, 2015"
5418,"Megyn Kelly Drops The Hammer On Roger Ailes, ...",The era of Roger Ailes at Fox News is definite...,News,"July 19, 2016"
1680,"Sean Spicer Baffles Reporters, Claims Trump I...","On Tuesday, White House Propaganda Minister Se...",News,"April 25, 2017"
13466,WOW! PASTOR MARK BURNS Delivers Three Great Wo...,Pastor Mark Burns is such a fantastic speaker!...,politics,"Jul 21, 2016"
20702,"IF AMERICA ELECTS HILLARY, She Promises To Rew...",Hillary s over-the-top plan to tax the consume...,left-news,"Apr 21, 2016"
4517,"Trump Blames Charlotte Rioting On Drug Use, W...","Another day, another racist dog whistle echoed...",News,"September 22, 2016"
4841,REPORT: Trump’s Modeling Agency Is A Cover Fo...,The majority of Donald Trump s campaign is bui...,News,"August 30, 2016"
20047,RETIRED COP PENS Gut-Wrenching VIRAL Letter To...,It s easy to see why this letter went viral. B...,left-news,"Aug 31, 2016"
2053,Sarah Palin Removes Offensive Tweet After Bei...,The overwhelming response to her temper tantru...,News,"March 22, 2017"

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    23481 non-null  str
 1   text     23481 non-null  str
 2   subject  23481 non-null  str
 3   date     23481 non-null  str
dtypes: str(4)
memory usage: 733.9 KB

In [47]:
Df=pd.read_csv('true.csv')
Df

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [48]:
df['status']= True
Df['status']= False
DF=pd.concat([df,Df])
DF

,title,text,subject,date,status
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",True
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",True
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",True
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",True
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",True
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",False
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",False
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",False
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",False
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",False

In [49]:
DF.sample(10)

,title,text,subject,date,status
22171,The Corporate Plantation: NCAA College Sports ...,James Hall 21st Century WireThe obsession over...,US_News,"March 15, 2017",True
5600,House GOP To Waste MORE Time And Money With S...,When House Democrats staged a 26-hour sit-in t...,News,"July 5, 2016",True
18309,OOPS! MIT Researchers Debunk Global Warming Da...,B b..but Al Gore and Barack Obama say Scientis...,left-news,"Jul 16, 2017",True
8350,House Committee requests EpiPen documents from...,(Reuters) - U.S. representatives Jason Chaffet...,politicsNews,"August 29, 2016",False
16672,WILL FBI DIRECTOR Finally Bring The Boom Down ...,The answer is yes but they still haven t recov...,Government News,"Apr 2, 2016",True
12308,TUCKER CARLSON Demolishes Business Owner Who W...,,politics,"Nov 24, 2016",True
20068,“HILL”-ARIOUS VIDEO: HILLARY TAKES BREAK From ...,This video brilliantly dispels every one of Hi...,left-news,"Aug 26, 2016",True
8860,Senior Republicans signal issues in Congress f...,WASHINGTON (Reuters) - Representative Mac Thor...,politicsNews,"July 6, 2016",False
9615,White House prods Senate on Garland amid Repub...,WASHINGTON (Reuters) - The White House pressed...,politicsNews,"May 10, 2016",False
8986,Paul Krugman: Obama Rolled Back RONALD REAGAN...,"Paul Krugman, by his own admission, has been d...",News,"January 4, 2016",True

In [50]:
DF.dtypes

title       str
text        str
subject     str
date        str
status     bool
dtype: object

In [51]:
x=DF['title']+" "+DF['text']
y=DF['status']

In [52]:
x

0         Donald Trump Sends Out Embarrassing New Year’...
1         Drunk Bragging Trump Staffer Started Russian ...
2         Sheriff David Clarke Becomes An Internet Joke...
3         Trump Is So Obsessed He Even Has Obama’s Name...
4         Pope Francis Just Called Out Donald Trump Dur...
                               ...
21412    'Fully committed' NATO backs new U.S. approach...
21413    LexisNexis withdrew two products from Chinese ...
21414    Minsk cultural hub becomes haven from authorit...
21415    Vatican upbeat on possibility of Pope Francis ...
21416    Indonesia to buy $1.14 billion worth of Russia...
Length: 44898, dtype: str

In [53]:
y

0         True
1         True
2         True
3         True
4         True
         ...
21412    False
21413    False
21414    False
21415    False
21416    False
Name: status, Length: 44898, dtype: bool

### BUILDING MODEL

In [54]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer

In [55]:
vectorizer = TfidfVectorizer()
x=vectorizer.fit_transform(x)

In [56]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=42)
model=LogisticRegression(max_iter=50000)
model.fit(x_train,y_train)
predict=model.predict(x_test)
score=accuracy_score(y_test,predict)
print(score)

0.9881959910913141

In [57]:
new_headline = ["Trump to pick foe of Obama climate agenda to r...	WASHINGTON (Reuters) - Donald Trump will name ..."]
new_encoded = vectorizer.transform(new_headline)
prediction = model.predict(new_encoded)
print("Prediction:",prediction)

Prediction: [False]

In [59]:
new_headline = ["Donald Trump Sends Out Embarrassing New Year’...	Donald Trump just couldn t wish all Americans ..."]
new_encoded = vectorizer.transform(new_headline)
prediction = model.predict(new_encoded)
print("Prediction:",prediction)

Prediction: [ True]